var kmap_registration_arguments =
[
    "bookmark_heading"
,   "canvas_pane_path"
,   "command_heading_path"
,   "filesystem_path"
,   "heading"
,   "heading_path"
,   "numeric_decimal"
,   "numeric_unsigned_integer"
,   "tag_path"
,   "unconditional"
];

var kmap_registration_commands =
[
    "apply_options"
,   "cascade_tags"
,   "check_state"
,   "close_project"
,   "close_task"
,   "copy_body_from"
,   "copy_body_to"
,   "count_ancestors"
,   "count_descendants"
,   "create_alias"
,   "create_bookmark"
,   "create_child"
,   "create_command"
,   "create_contact"
,   "create_project"
,   "create_reference"
,   "create_sibling"
,   "create_tag"
,   "create_task"
,   "create_subtask"
,   "delete"
,   "delete_alias"
,   "delete_children"
,   "delete_node"
,   "dress"
,   "echo"
,   "edit"
,   "edit_body"
,   "focus_pane"
,   "hide_pane"
,   "load_kscript"
,   "move_body"
,   "move_children"
,   "move_down"
,   "move_node"
,   "move_up"
,   "open_task"
,   "print_heading"
,   "print_id"
,   "rebase_pane"
,   "repair_state"
,   "resolve"
,   "resolve_alias"
,   "reveal_pane"
,   "rotate_pane"
,   "run_unit_tests"
,   "select_bookmark"
,   "sort_children"
,   "swap_node"
,   "tag_node"
,   "travel_bottom"
,   "travel_down"
,   "travel_left"
,   "travel_right"
,   "travel_top"
,   "travel_up"
,   "update_body"
,   "update_heading"
,   "update_title"
];