var kmap_components = // Curiously, failure occurs if `const` used instead of `var`.
[
    "autosave"
,   "canvas"
,   "cli"
,   "command_store"
,   "database"
,   "database.filesystem"
,   "event_store"
,   "filesystem"
,   "jump_stack"
,   "log_store"
,   "log_task"
,   "network"
,   "option_store"
,   "root_node"
,   "tag_store"
,   "task_store"
,   "text_area"
,   "timer"
,   "visnetwork"
];
