/******************************************************************************
 * Author(s): Christopher J. Havlicek
 *
 * See LICENSE and CONTACTS.
 ******************************************************************************/
kmap_pretest_options = '--durations=yes'
kmap_pretest_options += ' --verbosity=high'
// kmap_pretest_options += ' --skip-benchmarks'
kmap_pretest_options += ' --benchmark-samples=1'
// kmap_pretest_options += ' --success'
let kmap_pretest_targets = ''
// kmap_pretest_targets = '*' // All
// kmap_pretest_targets += ',Scenario: AliasSet basic ops'
// kmap_pretest_targets += ',Scenario: AliasStore::fetch_alias_children'
// kmap_pretest_targets += ',Scenario: AliasStore::fetch_aliases'
// kmap_pretest_targets += ',Scenario: AliasStore::fetch_dsts'
// kmap_pretest_targets += ',Scenario: AllOf::compare_less'
// kmap_pretest_targets += ',Scenario: Child::compare'
// kmap_pretest_targets += ',Scenario: Database::push_child'
// kmap_pretest_targets += ',Scenario: EventStore::fire_event'
// kmap_pretest_targets += ',Scenario: Network::create_alias'
// kmap_pretest_targets += ',Scenario: Network::create_child'
// kmap_pretest_targets += ',Scenario: Network::erase_node'
// kmap_pretest_targets += ',Scenario: Network::fetch_children_ordered'
// kmap_pretest_targets += ',Scenario: Network::fetch_ordering_position'
// kmap_pretest_targets += ',Scenario: Network::fetch_parent'
// kmap_pretest_targets += ',Scenario: Network::fetch_visible_nodes_from'
// kmap_pretest_targets += ',Scenario: Network::is_alias'
// kmap_pretest_targets += ',Scenario: Network::resolve'
// kmap_pretest_targets += ',Scenario: Network::set_ordering_position'
// kmap_pretest_targets += ',Scenario: TaskStore::activate_task'
// kmap_pretest_targets += ',Scenario: TaskStore::create_subtask'
// kmap_pretest_targets += ',Scenario: act::Order'
// kmap_pretest_targets += ',Scenario: act::create_node'
// kmap_pretest_targets += ',Scenario: act::fetch_or_create_node'
// kmap_pretest_targets += ',Scenario: cmd::activate_task'
// kmap_pretest_targets += ',Scenario: edit.body'
// kmap_pretest_targets += ',Scenario: is_valid_heading'
// kmap_pretest_targets += ',Scenario: tokenize_heading_path'
// kmap_pretest_targets += ',Scenario: view::Alias::fetch'
// kmap_pretest_targets += ',Scenario: view::AllOf::fetch'
// kmap_pretest_targets += ',Scenario: view::Ancestor::fetch'
// kmap_pretest_targets += ',Scenario: view::Link::operator<'
// kmap_pretest_targets += ',Scenario: view::SiblingIncl::fetch'
// kmap_pretest_targets += ',Scenario: view::event::Requisite::fetch'
// kmap_pretest_targets += ',Scenario: view::operator|Link Link'
// kmap_pretest_targets += ',Scenario: view::operator|TetherCT Link'
// kmap_pretest_targets += ',Scenario: decide_path'
// kmap_pretest_targets += ',Scenario: save.as after save.as output DBs are mirrored for all listed components'
// kmap_pretest_targets += ',Scenario: Erase canvas node within save/load'
// kmap_pretest_targets += ',[abs_path],[abs_path_flat]'
// kmap_pretest_targets += ',[action]'
// kmap_pretest_targets += ',[alias]'
// kmap_pretest_targets += ',[autosave]'
// kmap_pretest_targets += ',[benchmark]'
// kmap_pretest_targets += ',[canvas]'
// kmap_pretest_targets += ',[cli]'
// kmap_pretest_targets += ',[cmd]'
// kmap_pretest_targets += ',[cmd][log][task]'
// kmap_pretest_targets += ',[cmd][task]'
// kmap_pretest_targets += ',[com][network][alias]'
// kmap_pretest_targets += ',[com][text_area]'
// kmap_pretest_targets += ',[db][fs]'
// kmap_pretest_targets += ',[event]' 
// kmap_pretest_targets += ',[iface]'
// kmap_pretest_targets += ',[kmap_iface]'
// kmap_pretest_targets += ',[link]'
kmap_pretest_targets += ',[js_iface]'
// kmap_pretest_targets += ',[jump_stack]'
// kmap_pretest_targets += ',[move_node]'
// kmap_pretest_targets += ',[node_view]'
// kmap_pretest_targets += ',[network]'
// kmap_pretest_targets += ',[order]'
// kmap_pretest_targets += ',[parser]'
// kmap_pretest_targets += ',[path]'
// kmap_pretest_targets += ',[path][node_view]'
// kmap_pretest_targets += ',[profile]'
// kmap_pretest_targets += ',[query_cache]'
// kmap_pretest_targets += ',[repair]'
// kmap_pretest_targets += ',[tag]'
// kmap_pretest_targets += ',[take]'
// kmap_pretest_targets += ',[task]'
// kmap_pretest_targets += ',[save]'
// kmap_pretest_targets += ',[text_area]'
// kmap_pretest_targets += ',[visnetwork]'
// kmap_pretest_targets += ',[option]'
